create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z][a-z0-9_-]{1,48}$'),
  name text not null,
  type text not null check (type in ('company', 'community', 'team', 'course', 'agency', 'chat')),
  visibility text not null default 'private' check (visibility in ('private', 'invite_only', 'gated', 'public', 'unlisted')),
  owner_user_id uuid references auth.users(id) on delete set null,
  plan text not null default 'free' check (plan in ('free', 'team', 'enterprise')),
  description text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table if not exists public.workspace_members (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'moderator', 'publisher', 'member', 'viewer')),
  status text not null default 'active' check (status in ('invited', 'active', 'suspended', 'removed')),
  source text not null default 'direct' check (source in ('direct', 'invite', 'email_domain', 'telegram', 'discord', 'entitlement', 'paid_entitlement', 'token_bootstrap')),
  joined_at timestamptz not null default now(),
  removed_at timestamptz,
  unique (workspace_id, user_id)
);

create table if not exists public.workspace_invites (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  email text,
  code_hash text not null check (code_hash ~ '^sha256:[a-f0-9]{64}$'),
  role text not null default 'member' check (role in ('owner', 'admin', 'moderator', 'publisher', 'member', 'viewer')),
  max_uses int,
  uses_count int not null default 0 check (uses_count >= 0),
  expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.workspace_tokens (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  name text not null,
  token_hash text not null check (token_hash ~ '^sha256:[a-f0-9]{64}$'),
  scopes text[] not null default array['workspace:read']::text[],
  expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  check (scopes <@ array[
    'workspace:*',
    'workspace:read',
    'workspace:setup',
    'resource:read',
    'resource:publish',
    'resource:archive',
    'read',
    'setup',
    'publish',
    'entitlements:read'
  ]::text[])
);

create table if not exists public.workspace_audit (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  token_id uuid references public.workspace_tokens(id) on delete set null,
  action text not null,
  target text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.workspace_resources (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  resource_id text not null,
  name text not null,
  resource_type text not null,
  visibility text not null default 'private' check (visibility in ('private', 'members', 'public', 'unlisted')),
  trust jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  unique (workspace_id, resource_id)
);

alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.workspace_invites enable row level security;
alter table public.workspace_tokens enable row level security;
alter table public.workspace_audit enable row level security;
alter table public.workspace_resources enable row level security;

drop policy if exists "Workspace members read their workspaces" on public.workspaces;
create policy "Workspace members read their workspaces"
  on public.workspaces for select
  using (
    visibility in ('public', 'unlisted')
    or exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = workspaces.id
        and wm.user_id = auth.uid()
        and wm.status = 'active'
        and wm.removed_at is null
    )
  );

drop policy if exists "Workspace members read membership" on public.workspace_members;
create policy "Workspace members read membership"
  on public.workspace_members for select
  using (
    exists (
      select 1 from public.workspace_members self
      where self.workspace_id = workspace_members.workspace_id
        and self.user_id = auth.uid()
        and self.status = 'active'
        and self.removed_at is null
    )
  );

drop policy if exists "Workspace admins read token metadata" on public.workspace_tokens;
create policy "Workspace admins read token metadata"
  on public.workspace_tokens for select
  using (
    exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = workspace_tokens.workspace_id
        and wm.user_id = auth.uid()
        and wm.status = 'active'
        and wm.removed_at is null
        and wm.role in ('owner', 'admin')
    )
  );

drop policy if exists "Workspace members read resources" on public.workspace_resources;
create policy "Workspace members read resources"
  on public.workspace_resources for select
  using (
    visibility in ('public', 'unlisted')
    or exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = workspace_resources.workspace_id
        and wm.user_id = auth.uid()
        and wm.status = 'active'
        and wm.removed_at is null
    )
  );

drop policy if exists "Workspace members read audit" on public.workspace_audit;
create policy "Workspace members read audit"
  on public.workspace_audit for select
  using (
    exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = workspace_audit.workspace_id
        and wm.user_id = auth.uid()
        and wm.status = 'active'
        and wm.removed_at is null
    )
  );

create index if not exists workspaces_type_visibility_idx on public.workspaces (type, visibility) where archived_at is null;
create index if not exists workspace_members_user_idx on public.workspace_members (user_id, workspace_id) where removed_at is null;
create index if not exists workspace_tokens_workspace_hash_idx on public.workspace_tokens (workspace_id, token_hash) where revoked_at is null;
create index if not exists workspace_invites_hash_idx on public.workspace_invites (workspace_id, code_hash) where revoked_at is null;
create index if not exists workspace_audit_workspace_created_idx on public.workspace_audit (workspace_id, created_at desc);
create index if not exists workspace_resources_workspace_name_idx on public.workspace_resources (workspace_id, name) where archived_at is null;
