create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z][a-z0-9_-]{1,48}$'),
  name text not null,
  plan text not null default 'free' check (plan in ('free', 'team', 'enterprise')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.org_members (
  org_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'publisher', 'member')),
  created_at timestamptz not null default now(),
  primary key (org_id, user_id)
);

create table if not exists public.org_tokens (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  token_hash text not null check (token_hash ~ '^sha256:[a-f0-9]{64}$'),
  scopes text[] not null default array['read']::text[] check (scopes <@ array['read', 'setup', 'publish']::text[]),
  expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.org_setup_bundles (
  org_id uuid primary key references public.organizations(id) on delete cascade,
  version text not null check (version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,60}$'),
  bundle jsonb not null check (jsonb_typeof(bundle) = 'object'),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.org_audit_log (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  token_id uuid references public.org_tokens(id) on delete set null,
  action text not null,
  target text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.organizations enable row level security;
alter table public.org_members enable row level security;
alter table public.org_tokens enable row level security;
alter table public.org_setup_bundles enable row level security;
alter table public.org_audit_log enable row level security;

drop policy if exists "Org members read their orgs" on public.organizations;
create policy "Org members read their orgs"
  on public.organizations for select
  using (
    exists (
      select 1
      from public.org_members om
      where om.org_id = organizations.id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "Org members read membership" on public.org_members;
create policy "Org members read membership"
  on public.org_members for select
  using (
    exists (
      select 1
      from public.org_members self
      where self.org_id = org_members.org_id
        and self.user_id = auth.uid()
    )
  );

drop policy if exists "Org admins read token metadata" on public.org_tokens;
create policy "Org admins read token metadata"
  on public.org_tokens for select
  using (
    exists (
      select 1
      from public.org_members om
      where om.org_id = org_tokens.org_id
        and om.user_id = auth.uid()
        and om.role in ('owner', 'admin')
    )
  );

drop policy if exists "Org members read setup bundles" on public.org_setup_bundles;
create policy "Org members read setup bundles"
  on public.org_setup_bundles for select
  using (
    exists (
      select 1
      from public.org_members om
      where om.org_id = org_setup_bundles.org_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "Org members read audit log" on public.org_audit_log;
create policy "Org members read audit log"
  on public.org_audit_log for select
  using (
    exists (
      select 1
      from public.org_members om
      where om.org_id = org_audit_log.org_id
        and om.user_id = auth.uid()
    )
  );

create index if not exists org_members_user_idx on public.org_members (user_id, org_id);
create index if not exists org_tokens_org_hash_idx on public.org_tokens (org_id, token_hash) where revoked_at is null;
create index if not exists org_setup_bundles_updated_idx on public.org_setup_bundles (updated_at desc);
create index if not exists org_audit_log_org_created_idx on public.org_audit_log (org_id, created_at desc);
